// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqgmemCG6xbt-wvHxDlH8TzKh1lB8Gxw',
    appId: '1:37320282327:web:9680dbeb8c5c50f01e2092',
    messagingSenderId: '37320282327',
    projectId: 'my-boot-53f8b',
    authDomain: 'my-boot-53f8b.firebaseapp.com',
    storageBucket: 'my-boot-53f8b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9W8WQ_HvG048tix7NAKEgIJ44TE8_ZQ',
    appId: '1:37320282327:android:d1df21e159e8c65d1e2092',
    messagingSenderId: '37320282327',
    projectId: 'my-boot-53f8b',
    storageBucket: 'my-boot-53f8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_PaKOGLOQFjRdEWVoEtfeeP1DNY2spEI',
    appId: '1:37320282327:ios:2fce159af18e37b11e2092',
    messagingSenderId: '37320282327',
    projectId: 'my-boot-53f8b',
    storageBucket: 'my-boot-53f8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterBootstrapPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_PaKOGLOQFjRdEWVoEtfeeP1DNY2spEI',
    appId: '1:37320282327:ios:2fce159af18e37b11e2092',
    messagingSenderId: '37320282327',
    projectId: 'my-boot-53f8b',
    storageBucket: 'my-boot-53f8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterBootstrapPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVqgmemCG6xbt-wvHxDlH8TzKh1lB8Gxw',
    appId: '1:37320282327:web:60ca5baa93dfa3c21e2092',
    messagingSenderId: '37320282327',
    projectId: 'my-boot-53f8b',
    authDomain: 'my-boot-53f8b.firebaseapp.com',
    storageBucket: 'my-boot-53f8b.firebasestorage.app',
  );
}
